### ISSUE TITLE
pipx doesn't remove injected apps' symlinks after main package is uninstalled

### ISSUE THREAD

**Issue by vanyakosmos** [pipxproject/pipx#293] opened 2019-12-14 18:59 UTC
**Describe the bug**

pipx doesn't remove injected apps' symlinks after main package is uninstalled

**How to reproduce**

```
# install
pipx install black
pipx inject --include-apps black flake8
pipx list
# here you will see black, blackd, flake8 under black package

# remove
pipx uninstall black
pipx list
# no black package and injected ones

# install again
pipx install black
pipx list
# here you will see black, blackd, flake8 under black package
# flake8 alias was not removed, but flake8 itself is not installed
# and it is displayed in the list for some reasons
```

**Expected behavior**

Aliases of injected app should be removed after main package was deleted.

**Comment by itsayellow** [comment] 2019-12-15 22:29
Duplicate of #221

**Closed** 2019-12-15 22:50 UTC
