### ISSUE TITLE
azure-cli: No module named 'azure'

### ISSUE THREAD

**Issue by laktak** [pipxproject/pipx#162] opened 2019-05-13 14:20 UTC
I tried to install `azure-cli` but ran into a `ModuleNotFoundError`:

```
$ pipx install azure-cli
  installed package azure-cli 2.0.64, Python 3.7.3
  These binaries are now globally available
    - az
    - az.bat
    - az.completion.sh
done! ✨ 🌟 ✨
$
$ az
/usr/bin/python: Error while finding module specification for 'azure.cli' (ModuleNotFoundError: No module named 'azure')
$ type az
az is hashed (/home/foo/.local/bin/az)
$ ls -l /home/foo/.local/bin/az
lrwxrwxrwx 1 foo foo 46 2019-05-13 14:44 /home/foo/.local/bin/az -> /home/foo/.local/pipx/venvs/azure-cli/bin/az
$ ls /home/foo/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure
batch  cli  common  datalake  graphrbac  __init__.py  keyvault  mgmt  multiapi  profiles  __pycache__  storage
```

The module appears to be here - is there something special about `azure-cli`?

**Comment by nuno-andre** [comment] 2019-07-08 22:54
It's a common error in multiple versions of Azure CLI, usually solved reinstalling some `nspkg` (namespace package). But Azure CLI is not intended to be installed as a standard pip package, and though it can be installed [manually via script](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest), it's recommended to install it [with a package manager](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest).

**Comment by laktak** [comment] 2019-07-09 09:15
Interesting, didn't know that. But still, if it's not intended it should be a pip package ;)

Anyways, I can install and use `azure-cli` with `pipenv` so I assumed it should work with with `pipx` as well.

**Comment by suominen** [comment] 2019-11-30 11:34
This now works since the [Azure CLI 2.0.77 release](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.77).

**Comment by gaborbernat** [comment] 2019-11-30 14:41
Cool, so I guess the issue itself can now be closed as the fix was on the package side 👍

**Closed by gaborbernat** 2019-11-30 14:41 UTC

**Comment by beastea** [comment] 2020-01-02 17:09
`az interactive` command still fails

`~ > az interactive
This command is in preview. It may be changed/removed in a future release.
The command failed with an unexpected error. Here is the traceback:

cannot import name 'DEFAULTS_SECTION' from 'azure.cli.core._config' (/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/core/_config.py)
Traceback (most recent call last):
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 654, in _run_job
    six.reraise(*sys.exc_info())
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 487, in default_command_handler
    return op(**command_args)
  File "/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/command_modules/interactive/custom.py", line 41, in start_shell
    azext_interactive.start_shell(cmd, style=style)
  File "/Users/user/.azure/cliextensions/interactive/azext_interactive/__init__.py", line 10, in start_shell
    from .azclishell.app import AzInteractiveShell
  File "/Users/user/.azure/cliextensions/interactive/azext_interactive/azclishell/app.py", line 35, in <module>
    from azure.cli.core._config import DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION' from 'azure.cli.core._config' (/Users/user/.local/pipx/venvs/azure-cli/lib/python3.7/site-packages/azure/cli/core/_config.py)

To open an issue, please run: 'az feedback'`

Not sure if this is a package or a pipx problem

**Comment by suominen** [comment] 2020-01-02 17:48
It would probably be best to open a new issue, probably with azure-cli itself, instead of commenting on this closed issue.

But FWIW, I cannot reproduce this with
* macOS 10.15.2
* MacPorts 2.6.2
* python 3.7.6 (from MacPorts)
* pip 19.3.1 (from MacPorts)
* pipx 0.14.0.0 (from `python -m pip install -U --user pipx`)
* azure-cli 2.0.77 (from `pipx install azure-cli`)

I even tried upgrading azure-cli to 2.0.78 (`pipx upgrade-all`) and still cannot reproduce. The interactive module loads and starts without errors.

**Comment by suominen** [comment] 2020-01-02 17:56
Also, the downloaded copy of `.azure/cliextensions/interactive/azext_interactive/azclishell/app.py` on my system does not import anything from `azure.cli.core._config`.

I'm not sure what the recommended procedure for recovering from bad azure cli extensions is, but I'd probably try `rm -rf ~/.azure/cliextensions/interactive` to see if it downloads it again -- hopefully a version that works this time.

**Comment by beastea** [comment] 2020-01-03 10:02
This time it seems the issue was about cli extention.
Fixed by updating extension.
Thanks for your help!
