### ISSUE TITLE
pipx does not detect scripts in editable package

### ISSUE THREAD

**Issue by raxod502** [pipxproject/pipx#148] opened 2019-04-25 19:43 UTC
See: https://github.com/pipxproject/pipx/issues/108, https://github.com/pipxproject/pipx/issues/126, https://github.com/pipxproject/pipx/issues/144#issuecomment-486321615.

Repro with verbose output (using public GitHub repository):

```
% pipx install --verbose --editable --spec git+https://github.com/raxod502/diary-manager diary-manager
pipx (run_pipx_command:125): Virtual Environment location is /Users/raxod502/.local/pipx/venvs/diary-manager
pipx (_run:135): running /usr/local/opt/python/bin/python3.7 -m venv /Users/raxod502/.local/pipx/venvs/diary-manager
pipx (_run:135): running /Users/raxod502/.local/pipx/venvs/diary-manager/bin/python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-19.1
pipx (_run:135): running /Users/raxod502/.local/pipx/venvs/diary-manager/bin/python -m pip install --editable git+https://github.com/raxod502/diary-manager#egg=diary-manager
Obtaining diary-manager from git+https://github.com/raxod502/diary-manager#egg=diary-manager
  Cloning https://github.com/raxod502/diary-manager to ./.local/pipx/venvs/diary-manager/src/diary-manager
  Running command git clone -q https://github.com/raxod502/diary-manager /Users/raxod502/.local/pipx/venvs/diary-manager/src/diary-manager
Collecting python-dateutil (from diary-manager)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->diary-manager)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, diary-manager
  Running setup.py develop for diary-manager
Successfully installed diary-manager python-dateutil-2.8.0 six-1.12.0
pipx (rmdir:25): removing directory /Users/raxod502/.local/pipx/venvs/diary-manager
No binaries associated with package diary-manager.
```

The expected result is that installation succeeds, and [the binary `diary-manager`](https://github.com/raxod502/diary-manager/blob/919f724bb58e36b8626dd8d7c8475f71c0c54443/setup.py#L11) is made available on my `PATH`.

**Comment by cs01** [comment] 2019-04-25 20:01
This might have something to do with a regression, see https://github.com/pipxproject/pipx/issues/143.

If possible I would recommend using `entry_points` in your setup.py instead of `scripts` since they are better cross-platform, which should also have the side effect of working with pipx. You can see pipx's setup.py for an example.

https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=scripts#automatic-script-creation

**Comment by raxod502** [comment] 2019-04-27 20:56
Thanks for the tip! I can confirm that this is a good workaround.

**Comment by lexrj** [comment] 2019-08-27 05:32
I'm encountering this same issue. I tried to work around it, but it makes it extremely difficult (if not impossible) to test my script the way I was doing so before. Context in my case: A plugin for protoc protobuf compiler where we actually just add it to the path and kick off protoc (this protoc is guaranteed to be in the path in our use case).

**Comment by itsayellow** [comment] 2020-11-19 19:58
Closing as resolved.

**Closed by itsayellow** 2020-11-19 19:58 UTC
