### ISSUE TITLE
How to stop showing "Logging error" output when reinstalling or upgrading a package 

### ISSUE THREAD

**Issue by OdinTech3** [pipxproject/pipx#663] opened 2021-04-02 14:48 UTC
**Describe the bug**

On Windows 10, Pipx displays a logging error file whenever I install or reinstall a package using pix

```
{ ~ } » pipx upgrade flake8
⚠️  Overwriting file C:\Users\nickmuoh\.local\bin\flake8.exe with C:\Users\nickmuoh\.local\pipx\venvs\flake8\Scripts\flake8.exe
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nickmuoh\Scoop\apps\python38\current\scripts\pipx.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\main.py", line 759, in cli
    return run_pipx_command(parsed_pipx_args)
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\main.py", line 216, in run_pipx_command
    return commands.upgrade(
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\upgrade.py", line 160, in upgrade
    _ = _upgrade_venv(
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\upgrade.py", line 125, in _upgrade_venv
    versions_updated += _upgrade_package(
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\upgrade.py", line 50, in _upgrade_package
    expose_apps_globally(
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\common.py", line 56, in expose_apps_globally
    _copy_package_apps(local_bin_dir, app_paths, suffix=suffix)
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\common.py", line 95, in _copy_package_apps
    logger.warning(f"{hazard}  Overwriting file {str(dest)} with {str(src)}")
Message: '⚠️  Overwriting file C:\\Users\\nickmuoh\\.local\\bin\\flake8.exe with C:\\Users\\nickmuoh\\.local\\pipx\\venvs\\flake8\\Scripts\\flake8.exe'
Arguments: ()
upgraded package flake8 from 3.8.4 to 3.9.0 (location: C:\Users\nickmuoh\.local\pipx\venvs\flake8)
```

**How to reproduce**

The issue occurs whenever I upgrade or reinstall a package
```
{ ~ } » pipx upgrade --verbose flake8
pipx >(setup:711): pipx version is 0.16.1.0
pipx >(setup:712): Default python interpreter is 'c:\\users\\nickmuoh\\scoop\\apps\\python38\\current\\python.exe'
pipx >(run_pipx_command:166): Virtual Environment location is C:\Users\nickmuoh\.local\pipx\venvs\flake8
pipx >(needs_upgrade:67): Time since last upgrade of shared libs, in seconds: 525. Upgrade will be run by pipx if greater than 2592000.
pipx >(upgrade:88): Upgrading shared libraries in C:\Users\nickmuoh\.local\pipx\shared
upgrading shared libraries...
pipx >(run_subprocess:130): running C:\Users\nickmuoh\.local\pipx\shared\Scripts\python.exe -m pip --disable-pip-version-check install --upgrade pip setuptools wheel
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: flake8
upgrading flake8...
pipx >(run_subprocess:130): running C:\Users\nickmuoh\.local\pipx\venvs\flake8\Scripts\python.exe -m pip install --upgrade flake8
pipx >(run_subprocess:130): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:306): get_venv_metadata_for_package: 179ms
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: flake8
pipx >(_copy_package_apps:95): ⚠️  Overwriting file C:\Users\nickmuoh\.local\bin\flake8.exe with C:\Users\nickmuoh\.local\pipx\venvs\flake8\Scripts\flake8.exe
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>
Call stack:
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\nickmuoh\Scoop\apps\python38\current\scripts\pipx.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\main.py", line 759, in cli
    return run_pipx_command(parsed_pipx_args)
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\main.py", line 216, in run_pipx_command
    return commands.upgrade(
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\upgrade.py", line 160, in upgrade
    _ = _upgrade_venv(
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\upgrade.py", line 125, in _upgrade_venv
    versions_updated += _upgrade_package(
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\upgrade.py", line 50, in _upgrade_package
    expose_apps_globally(
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\common.py", line 56, in expose_apps_globally
    _copy_package_apps(local_bin_dir, app_paths, suffix=suffix)
  File "c:\users\nickmuoh\scoop\apps\python38\current\lib\site-packages\pipx\commands\common.py", line 95, in _copy_package_apps
    logger.warning(f"{hazard}  Overwriting file {str(dest)} with {str(src)}")
Message: '⚠️  Overwriting file C:\\Users\\nickmuoh\\.local\\bin\\flake8.exe with C:\\Users\\nickmuoh\\.local\\pipx\\venvs\\flake8\\Scripts\\flake8.exe'
Arguments: ()
flake8 is already at latest version 3.9.0 (location: C:\Users\nickmuoh\.local\pipx\venvs\flake8)
```

**Expected behavior**

I would expect pipx to just display the below code snipper whenever I upgrade or reinstall a package
```
{ ~ } » pipx upgrade flake8
⚠️  Overwriting file C:\Users\nickmuoh\.local\bin\flake8.exe with C:\Users\nickmuoh\.local\pipx\venvs\flake8\Scripts\flake8.exe
```

**Comment by itsayellow** [comment] 2021-04-02 16:35
Duplicate of #645 

This should be fixed by #646 , which will be released shortly.

**Closed by itsayellow** 2021-04-02 16:35 UTC
