### ISSUE TITLE
pipx deletes unrelated executables from .local/bin when uninstalling

### ISSUE THREAD

**Issue by jonapich** [pipxproject/pipx#670] opened 2021-04-14 19:11 UTC
**Describe the bug**
I am using `coveo-stew` which imports `poetry`. Even though `pipx install coveo-stew` does not create a `.local/bin/poetry.exe`, running `pipx uninstall coveo-stew` will delete `.local/bin/poetry.exe` if it exists.

**How to reproduce**
1. run `pipx install coveo-stew` in a pipx that doesn't have poetry
2. Look in the `.local/bin` folder; there is no poetry exec (it's in .local/pipx/venvs/etc; that's OK)
3. run `pipx install poetry`
4. The `poetry.exe` executable is created in `.local/bin`
5. run `pipx uninstall coveo-stew`
6. pipx deletes the `poetry.exe` file from `.local/bin` 😱 

**Expected behavior**
Executables should not be deleted unless they directly belong to the project.

**Comment by itsayellow** [comment] 2021-04-14 19:31
I think this is related to: #564 which was supposed to be fixed by #650.  #650 has not been released yet.
BUT!  Even with the unreleased code this bug still exists ☹️ 

I just tried this, and sadly uninstalling coveo-stew has so many dependencies that pipx incorrectly deletes a ton of useful executables when it is uninstalled, besides `poetry.exe`.

This is an excellent test case, I'm not sure at the moment why #650 didn't fix this, but I will dig in to find out.

**Comment by itsayellow** [comment] 2021-04-14 19:48
Ah the problem is I fixed `_get_exposed_app_paths_for_package()` but unfortunately `pipx uninstall` doesn't use that function, it uses largely duplicate code that has not been fixed.

**Closed** 2021-04-27 19:51 UTC
