### ISSUE TITLE
There is no obvious command to upgrade or downgrade a program to an specific version

### ISSUE THREAD

**Issue by absassi** [pipxproject/pipx#537] opened 2020-10-30 14:01 UTC
**How would this feature be useful?**
Sometimes one wants to use a program in a specific version or version range, instead of the latest one. For instance, when the upgrade would cause breaking changes or the most recent version has some bug that affects one's work.

**Describe the solution you'd like**
`pipx upgrade` command should have a clear way to tell which version to upgrade to. To me, the most intuitive option is to mimic the `pipx install` command by accepting `package_spec` (package name or pip installation spec) instead of just the `package` name as it currently does.

Example: `pipx upgrade "poetry<1.1"` to upgrade or downgrade Poetry to its latest 1.0.x version.

**Describe alternatives you've considered**
The only way I found that I could downgrade a package was by uninstalling it and then installing it again with the spec I wanted.
If there is already a way to do it, it is not obvious and it is not exemplified in the documentation.

**Comment by itsayellow** [comment] 2020-10-31 06:38
Thanks for the vote for this, it's probably something we need to do.

I'm closing this because it seems to be a duplicate of #356

**Closed by itsayellow** 2020-10-31 06:38 UTC
