### ISSUE TITLE
pipx install erroneously exposing binaries of dependencies despite no `--include-deps` switch

### ISSUE THREAD

**Issue by sandersantema** [pipxproject/pipx#548] opened 2020-11-12 14:08 UTC
This might already be possible, I couldn't find out how however.

**How would this feature be useful?**
Currently when installing a package all of it's included apps (dependencies?) are exposed to `$PATH`, even though when I for instance want to install `organize` using `pipx install organize-tool` I really only want the `organize` binary to be exposed. I assume (with my limited knowledge of python packages) that these apps are actually required for the main app but could also be contained to the venv and don't need to be exposed to `$PATH`.

What is actually installed is the following:
```
   package organize-tool 1.9.1, Python 3.8.5
    - EXIF.py
    - activate-global-python-argcomplete
    - docx2txt
    - dumppdf.py
    - latin2ascii.py
    - organize
    - pdf2txt.py
    - python-argcomplete-check-easy-install-script
    - python-argcomplete-tcsh
    - register-python-argcomplete
    - textract
```

I looked for a way to do this and thought I might be able to do so by editing the `pipx_metadata.json` but unfortunately that doesn't seem to be the case. 

**Describe the solution you'd like**
Given that it's probably not practical to determine which of the apps included is the main one it'd probably be better to make this configurable by the user themselves in for instance the `pipx_metadata.json`

**Comment by itsayellow** [comment] 2020-11-12 19:14
Could you post the entire text of what happens after `pipx install organize-tool --verbose`?

I can't reproduce your report, when I try on my system I only have `organize` globally available on my system.  (What you would like to happen this is pipx's default behavior):
```
> pipx install organize-tool
  installed package organize-tool 1.9.1, Python 3.9.0
  These apps are now globally available
    - organize
done! ✨ 🌟 ✨
```

**Comment by itsayellow** [comment] 2020-11-12 19:16
Also the output you paste looks like it may be from an old version of pipx.  Could you also report what is printed when executing the following:
```
pipx --version
```

**Comment by itsayellow** [comment] 2020-11-12 19:29
Also, could you make sure the command you're using is:
```
pipx install organize-tool
```

Do **NOT** use the `--include-deps` option, which would give the behavior you don't want.

**Comment by sandersantema** [comment] 2020-11-13 14:20
I was indeed running an older version of pipx, unfortunately simply upgrading doesn't seem to fix it.

Here's a pastebin with the output of `pipx install organize-tool --verbose`:
https://pastebin.com/WMvYhcL0
This is the output after using `pipx uninstall organize-tool`

And:
```
~> pipx --version
0.15.6.0
```

Just to be sure, I didn't find any weird alias or function in my shell which wrapped `pipx` either.

**Comment by itsayellow** [comment] 2020-11-13 19:16
Hm.  I really don't understand how this is happening.  pipx by default only links apps from the main package.

Your output looks similar to what would result from `pipx install organize-tool --include-deps`.  But strangely, when I execute that command on my own system I also get apps `runxlrd.py` and `vba_extract.py` which you do not.  So it's not exactly the same.

I can't reproduce the behavior you're showing on my own system using the regular `pipx install organize-tool`.  I'm stumped.

Do you have another system that you could try this with and see if you get the same results?  Otherwise right now I'm at a loss.

**Comment by itsayellow** [comment] 2020-11-13 19:17
Also, what operating system and OS version are you using?

**Comment by itsayellow** [comment] 2020-11-13 19:33
Another possible thing to check: Do you have a local directory called `organize-tool` that pipx is possibly finding instead of fetching from PyPI?

**Comment by sandersantema** [comment] 2020-11-13 22:31
> Also, what operating system and OS version are you using?

I'm using Linux openSuSE Tumbleweed.

> Another possible thing to check: Do you have a local directory called `organize-tool` that pipx is possibly finding instead of fetching from PyPI?

I had one from installing from source which was in my downloads directory, however deleting that directory and reinstalling organize-tool didn't make a difference. But I don't assume pipx actually traverses my whole home directory is that right?

**Comment by itsayellow** [comment] 2020-11-13 22:44
OK, here's one more thing I can think of to try.  Execute this:
```
pip cache purge
```

And then try `pipx install organize-tool --verbose` again. 🤞

**Comment by itsayellow** [comment] 2020-11-13 23:33
Another possible way to disable `pip`'s cache--Install using:
```
pipx install organize-tool --pip-args='--no-cache-dir'
```

**Comment by itsayellow** [comment] 2020-11-19 18:48
@sandersantema did any of those work?  Can we close this issue?

**Comment by sandersantema** [comment] 2020-11-19 20:17
Sorry I didn't see these comments earlier, I did however try out both of them just now. These didn't work either however. I still get the following binaries exposed:
```
    - EXIF.py
    - activate-global-python-argcomplete
    - docx2txt
    - dumppdf.py
    - latin2ascii.py
    - organize
    - pdf2txt.py
    - python-argcomplete-check-easy-install-script
    - python-argcomplete-tcsh
    - register-python-argcomplete
    - textract
```

**Comment by itsayellow** [comment] 2020-11-21 01:42
The last thing (that we should've done in the beginning) is to include the entire text of what is output (including the input command you typed) when your run
```
pipx install organize-tool --verbose
```
The `--verbose` switch is important, as is including the entire command + output.

**Comment by sandersantema** [comment] 2020-11-23 11:58
Sorry for the delay, I seem to regularly miss these github notifications. But anyways here is the output: https://pastebin.com/raw/gLTK9RTh

**Comment by itsayellow** [comment] 2020-11-23 19:05
I think I'm almost stumped.  The only other thing I can think of is to see if you have any environment variables that start with `PIP` in your environment that are affecting how pip installs things.  (pipx uses pip to install packages)

What is the output of:
```
env
```

Otherwise, I can't replicate this on my own Ubuntu linux system, nor on my macOS system.  

My best guess was that some weird version of `organize-tools` is in the pip cache, but `pip cache purge` should've taken care of that.

Another weird thing is that the output you show is not exactly what would happen if you added the `pipx install --include-deps` switch.  There are some binaries in dependencies that don't show up in your install list that do for me when I run `pipx install --include-deps`.

**Comment by sandersantema** [comment] 2020-11-24 19:37
There was nothing about PIP or python in my env. If you'd want to it might be more informative to try it out on openSuSE Tumbleweed the distro which I'm running, I suppose it might be possible its got something to do with Tumbleweed itself although I think it's doubtful.  Otherwise I'll try to debug some more myself once I've got some more free time.

**Comment by itsayellow** [comment] 2020-11-24 19:43
Yeah I think I'm out of ideas, thanks for your patience.

**Comment by sandersantema** [comment] 2020-11-24 19:48
No problem, thank you for your persistence.

**Comment by jwodder** [comment] 2020-11-25 17:02
I believe I know what's going on.  I just stumbled upon this behavior and was about to file a bug report.

The problem is: When pipx installs package foo that depends on bar that has an entry point bar-cmd, if a bar-cmd program already exists in `PIPX_BIN_DIR` (e.g., if bar is already installed at the user level), then bar-cmd will be listed as a pipx-installed command in the output from `pipx install` and `pipx list` even though it is not.  Fortunately, pipx has enough sense to not delete bar-cmd when `pipx uninstall foo` is run, which suggests that it can tell whether a given command is managed by pipx, it's just not doing it in all cases.

**Comment by itsayellow** [comment] 2020-11-25 19:38
Very interesting @jwodder .  I can see in the code how this might happen on Windows (without symlinks) but in theory this shouldn't happen on systems with symlinks, because the code is at least trying to resolve the symlinks to check where they refer to.

@sandersantema , do you have any of the dependencies of `organize-tool` installed with pipx?  Like `textract`, `exifread`?  Could you include the output of `pipx list`?  

With `pipx install textract --include-deps` you would get most of those additional binaries, and if pipx is confused where they came from as @jwodder suggests, that might explain it.

**Comment by itsayellow** [comment] 2020-11-25 19:43
Also @sandersantema , one related question would be if pipx thinks it can use symlinks for your filesystem.  If you execute
```
ls -l ~/.local/bin
```
Do you see symlinks (e.g. `vulture@ -> /Users/mclapp/.local/pipx/venvs/vulture/bin/vulture`) listed?  Or not?

**Comment by itsayellow** [comment] 2020-11-25 23:38
@sandersantema , if you have the "extra" apps reported present in your `PIPX_BIN_DIR` (`~/.local/bin`) and they are not symlinks, then your problem is basically #564 .

**Comment by sandersantema** [comment] 2020-11-29 10:14
> @sandersantema , do you have any of the dependencies of `organize-tool` installed with pipx? Like `textract`, `exifread`? Could you include the output of `pipx list`?

Output of `$ pipx list`:
```
venvs are in /home/sandersantema/.local/pipx/venvs
apps are exposed on your $PATH at /home/sandersantema/.local/bin
   package catt 0.12.0, Python 3.8.5
    - catt
   package neovim-remote 2.4.0, Python 3.8.5
    - nvr
   package organize-tool 1.9.1, Python 3.8.6
    - EXIF.py
    - activate-global-python-argcomplete
    - docx2txt
    - dumppdf.py
    - latin2ascii.py
    - organize
    - pdf2txt.py
    - python-argcomplete-check-easy-install-script
    - python-argcomplete-tcsh
    - register-python-argcomplete
    - textract
   package poetry 1.1.4, Python 3.8.5
    - pkginfo
    - poetry
   package python-language-server 0.36.1, Python 3.8.5
    - pyls
   package ranger-fm 1.9.3, Python 3.8.6
    - ranger
    - rifle
   package sublime-music 0.11.10, Python 3.8.5
    - publish.py
    - pwiz.py
    - sublime-music
   package trash-cli 0.20.11.14, Python 3.8.5
    - trash
    - trash-empty
    - trash-list
    - trash-put
    - trash-restore
    - trash-rm
   package youtube-dl 2020.11.19, Python 3.8.5
    - youtube-dl
```

> Also @sandersantema , one related question would be if pipx thinks it can use symlinks for your filesystem. If you execute
> 
> ```
> ls -l ~/.local/bin
> ```
> 
> Do you see symlinks (e.g. `vulture@ -> /Users/mclapp/.local/pipx/venvs/vulture/bin/vulture`) listed? Or not?

That's it! 
```
-rwxr-xr-x 1 sandersantema users     6011 Mar 18  2020 pdf2txt.py
```
Instead of:
```
lrwxrwxrwx 1 sandersantema users       57 Nov 13 21:13 trash -> /home/sandersantema/.local/pipx/venvs/trash-cli/bin/trash
lrwxrwxrwx 1 sandersantema users       63 Nov 13 21:13 trash-empty -> /home/sandersantema/.local/pipx/venvs/trash-cli/bin/trash-empty
lrwxrwxrwx 1 sandersantema users       62 Nov 13 21:13 trash-list -> /home/sandersantema/.local/pipx/venvs/trash-cli/bin/trash-list
lrwxrwxrwx 1 sandersantema users       61 Nov 13 21:13 trash-put -> /home/sandersantema/.local/pipx/venvs/trash-cli/bin/trash-put
lrwxrwxrwx 1 sandersantema users       65 Nov 13 21:13 trash-restore -> /home/sandersantema/.local/pipx/venvs/trash-cli/bin/trash-restore
lrwxrwxrwx 1 sandersantema users       60 Nov 13 21:13 trash-rm -> /home/sandersantema/.local/pipx/venvs/trash-cli/bin/trash-rm
```

**Comment by sandersantema** [comment] 2020-11-29 10:16
I guess this means you now know what the bug is right? So it'd just a case of waiting for a fix and potentially manually removing (luckily just a few) binaries which were incorrectly installed?

**Comment by itsayellow** [comment] 2020-11-29 20:24
If you have these as regular files (and not symlinks) in your `~/.local/bin`, then this is also issue #564 
    - EXIF.py
    - activate-global-python-argcomplete
    - docx2txt
    - dumppdf.py
    - latin2ascii.py
    - pdf2txt.py
    - python-argcomplete-check-easy-install-script
    - python-argcomplete-tcsh
    - register-python-argcomplete
    - textract

It's not necessarily that they were incorrectly installed.  Perhaps you installed something using `pipx install --user`, which is a perfectly valid thing to do, (and will add binaries to this directory).  Currently such an action will confuse `pipx` when it comes to attributing apps.  This is pipx's fault.

If this is your case, then maybe we can close this issue and you can wait on #564?

**Comment by clssn** [comment] 2021-01-19 19:47
I looked into this and found out (Linux only, not investigated for Windows) that pipx just claims to have those exposed (meaning, to have it linked into `~/.local/bin`). You can easily see with `ls -l ~/.local/bin` that only the entry point scripts for your installed package are linking to the pipx venv directory. And you can see that there are also non-link python entrypoint scripts of all those dependencies claimed by pipx. 

The reason is [this condition](https://github.com/pipxproject/pipx/blob/5c3cc823ab780f4d562e5e8c1ed0c31aee893133/src/pipx/commands/common.py#L239) and [this comparison](https://github.com/pipxproject/pipx/blob/5c3cc823ab780f4d562e5e8c1ed0c31aee893133/src/pipx/commands/common.py#L242). 

Pipx iterates over every file in the `~/.local/bin` directory to filter those out that will later be claimed to be exposed by the current pipx package installation. If it's a symlink, then it's correctly tested whether the symlink points to an entrypoint script in the venv's binary dir. If it's not a symlink, then the else branch is used and just compares the *name* of the entrypoint with the *names* of the entrypoints installed in the venv. For me this quite often matches an entrypoint script in the `~/.local/bin` directory which was previously installed with plain pip3, so without pipx. And pip doesn't link, but directly generate the entry point scripts into the `~/.local/bin` directory, so they are not symlinks and thus not properly checked.

This is probably also the reason for some of you not being able to reproduce: If you're using pipx exclusively, then there are probably only symlinks in the `~/.local/bin` folder. These are properly checked by [this comparison](https://github.com/pipxproject/pipx/blob/5c3cc823ab780f4d562e5e8c1ed0c31aee893133/src/pipx/commands/common.py#L240).

Unfortunately I'm not deep enough in the code to propose a solution. I hope one of you has ideas? If not, at least be told: It's not as bad as it sometimes looks. And: If you tidy up your `~/.local/bin` folder by removing python tools with pip and migrating everything to pipx, then you'll also have no problems like some of the users above.

I guess this is also interesting for #564.

**Closed** 2021-03-23 04:05 UTC
