### ISSUE TITLE
pipx run fails with json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mgedmin** [pipxproject/pipx#393] opened 2020-04-24 11:33 UTC
**Describe the bug**

```
$ pipx run pipx
⚠️  pipx is already on your PATH and installed at /home/mg/bin/pipx. Downloading and running anyway.
Traceback (most recent call last):
  File "/home/mg/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/main.py", line 590, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/main.py", line 150, in run_pipx_command
    return commands.run(
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/commands/run.py", line 89, in run
    retval = _download_and_run(
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/commands/run.py", line 122, in _download_and_run
    venv.install_package(
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/venv.py", line 179, in install_package
    package = self.install_package_no_deps(package_or_url, pip_args)
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/venv.py", line 218, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/venv.py", line 300, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**How to reproduce**

`pipx run pipx`

> If possible, include output of `pipx --verbose ...` 

```
$ pipx --verbose run pipx
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall-all,list,run,runpip,ensurepath,completions}
            ...
pipx: error: unrecognized arguments: --verbose
```

I think your GitHub issue template needs a clarification.

```
$ pipx run --verbose pipx
pipx > (run:55): ⚠️  pipx is already on your PATH and installed at /home/mg/bin/pipx. Downloading and running anyway.
pipx > (needs_upgrade:51): Time since last upgrade of shared libs, in seconds: 1192.21550655365. Upgrade will be run by pipx if greater than 2592000.0.
pipx > (run:88): venv location is /home/mg/.local/pipx/.cache/a8fb067c4a3f37e
pipx > (needs_upgrade:51): Time since last upgrade of shared libs, in seconds: 1192.2158176898956. Upgrade will be run by pipx if greater than 2592000.0.
pipx > (run_subprocess:112): running /home/mg/.local/pipx/venvs/pipx/bin/python3 -m venv --without-pip /home/mg/.local/pipx/.cache/a8fb067c4a3f37e
pipx > (run_subprocess:112): running /home/mg/.local/pipx/.cache/a8fb067c4a3f37e/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/mg/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/mg/.local/pipx/.cache/a8fb067c4a3f37e/bin/python --version
pipx > (run_subprocess:112): running /home/mg/.local/pipx/.cache/a8fb067c4a3f37e/bin/python -m pip list --format=json
Traceback (most recent call last):
  File "/home/mg/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/main.py", line 590, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/main.py", line 150, in run_pipx_command
    return commands.run(
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/commands/run.py", line 89, in run
    retval = _download_and_run(
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/commands/run.py", line 122, in _download_and_run
    venv.install_package(
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/venv.py", line 179, in install_package
    package = self.install_package_no_deps(package_or_url, pip_args)
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/venv.py", line 218, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/home/mg/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/venv.py", line 300, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**

No crash

**Comment by mgedmin** [comment] 2020-04-24 11:34
Ah, I manually ran `/home/mg/.local/pipx/.cache/a8fb067c4a3f37e/bin/python -m pip list --format=json` and saw that this is just another manifestation of #386.

```
/home/mg/.local/pipx/.cache/a8fb067c4a3f37e/bin/python -m pip list --format=json
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mg/.local/pipx/shared/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/home/mg/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/mg/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/mg/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/mg/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/home/mg/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
ModuleNotFoundError: No module named 'pip._vendor.six'
```

**Comment by mgedmin** [comment] 2020-04-24 11:39
Workaround for poor new Ubuntu 20.04 LTS users like little old me:

```
$ ~/.local/pipx/shared/bin/pip install -I pip
```

This installs the upstream version of pip 20.0.2 in the shared venv, instead of the patched Debian version of pip 20.0.2.

I image when upstream pip releases 20.0.3, this problem will go away on its own, because I expect pipx will keep pip upgraded, while Debian won't.

**Comment by gaborbernat** [comment] 2020-04-24 12:19
Duplicate of https://github.com/pipxproject/pipx/issues/386

**Closed by gaborbernat** 2020-04-24 12:19 UTC

**Comment by rayluo** [comment] 2023-07-28 08:39
> Duplicate of #386

Indeed. Specifically, [this message](https://github.com/pypa/pipx/issues/386#issuecomment-749337079) was also my root cause, and it helped solved the problem.
