### ISSUE TITLE
Windows CMD can't encode characters in position 36-37

### ISSUE THREAD

**Issue by CarliJoy** [pipxproject/pipx#647] opened 2021-03-17 17:45 UTC
**Describe the bug**
`pipx upgrade-all` throws decoding errors

--- Logging error ---

> Traceback (most recent call last):
>   File "c:\enercon\python38\lib\logging\__init__.py", line 1084, in emit
>     stream.write(msg + self.terminator)
>   File "c:\enercon\python38\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>
> Call stack:
>   File "c:\enercon\python38\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\enercon\python38\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\ENERCON\Python38\Scripts\pipx.exe\__main__.py", line 7, in <module>
>     sys.exit(cli())
>   File "c:\enercon\python38\lib\site-packages\pipx\main.py", line 759, in cli
>     return run_pipx_command(parsed_pipx_args)
>   File "c:\enercon\python38\lib\site-packages\pipx\main.py", line 224, in run_pipx_command
>     return commands.upgrade_all(
>   File "c:\enercon\python38\lib\site-packages\pipx\commands\upgrade.py", line 192, in upgrade_all
>     venvs_upgraded += _upgrade_venv(
>   File "c:\enercon\python38\lib\site-packages\pipx\commands\upgrade.py", line 125, in _upgrade_venv
>     versions_updated += _upgrade_package(
>   File "c:\enercon\python38\lib\site-packages\pipx\commands\upgrade.py", line 50, in _upgrade_package
>     expose_apps_globally(
>   File "c:\enercon\python38\lib\site-packages\pipx\commands\common.py", line 56, in expose_apps_globally
>     _copy_package_apps(local_bin_dir, app_paths, suffix=suffix)
>   File "c:\enercon\python38\lib\site-packages\pipx\commands\common.py", line 95, in _copy_package_apps
>     logger.warning(f"{hazard}  Overwriting file {str(dest)} with {str(src)}")
> Message: '⚠️  Overwriting file C:\\Users\\00068549\\.local\\bin\\pyre-script.py with C:\\Users\\00068549\\.local\\pipx\\venvs\\pyre-check\\Scripts\\pyre-script.py'
> Arguments: ()
> upgraded package pyre-check from 0.0.59 to 0.9.0 (location: C:\Users\00068549\.local\pipx\venvs\pyre-check)

**How to reproduce**
run code as above with pipx 0.16.1

**Expected behavior**
No error show and not boxes like this:
![image](https://user-images.githubusercontent.com/7687556/111513205-d6741f80-8750-11eb-9309-e12ba1db521e.png)

but maybe instead simple (!!) ?

**Comment by itsayellow** [comment] 2021-03-17 18:45
Duplicate of #645.  Fixed with #646.

**Closed by itsayellow** 2021-03-17 18:45 UTC

**Comment by CarliJoy** [comment] 2021-03-17 19:07
Sorry for the duplicate - was not smart enough to include already closed issues, who did know that you are that fast in fixing the bugs ;-)

**Comment by itsayellow** [comment] 2021-03-17 22:30
Yeah I always have to remind myself to search closed issues too...
