### ISSUE TITLE
Printing log message when overwriting file triggers UnicodeEncodeError

### ISSUE THREAD

**Issue by davidwales** [pipxproject/pipx#645] opened 2021-03-16 00:27 UTC
**Describe the bug**
On Windows 10 (Powershell):
When pipx upgrade overwrites a file it prints a log message. This triggers an exception.

**How to reproduce**
Run `pipx upgrade --include-injected <package>` on Windows Powershell when a file needs to be overwritten.

See output below:

``` python
pipx upgrade --include-injected jupyterlab
⚠️  Overwriting file C:\Users\dwales\.local\bin\jlpm.exe with C:\Users\dwales\.local\pipx\venvs\jupyterlab\Scripts\jlpm.exe
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>
Call stack:
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dwales\AppData\Local\Programs\Python\Python38\Scripts\pipx.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 759, in cli
    return run_pipx_command(parsed_pipx_args)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 216, in run_pipx_command
    return commands.upgrade(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 160, in upgrade
    _ = _upgrade_venv(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 125, in _upgrade_venv
    versions_updated += _upgrade_package(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 50, in _upgrade_package
    expose_apps_globally(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\common.py", line 56, in expose_apps_globally
    _copy_package_apps(local_bin_dir, app_paths, suffix=suffix)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\common.py", line 95, in _copy_package_apps
    logger.warning(f"{hazard}  Overwriting file {str(dest)} with {str(src)}")
Message: '⚠️  Overwriting file C:\\Users\\dwales\\.local\\bin\\jlpm.exe with C:\\Users\\dwales\\.local\\pipx\\venvs\\jupyterlab\\Scripts\\jlpm.exe'
Arguments: ()
⚠️  Overwriting file C:\Users\dwales\.local\bin\jupyter-lab.exe with C:\Users\dwales\.local\pipx\venvs\jupyterlab\Scripts\jupyter-lab.exe
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>
Call stack:
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dwales\AppData\Local\Programs\Python\Python38\Scripts\pipx.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 759, in cli
    return run_pipx_command(parsed_pipx_args)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 216, in run_pipx_command
    return commands.upgrade(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 160, in upgrade
    _ = _upgrade_venv(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 125, in _upgrade_venv
    versions_updated += _upgrade_package(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 50, in _upgrade_package
    expose_apps_globally(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\common.py", line 56, in expose_apps_globally
    _copy_package_apps(local_bin_dir, app_paths, suffix=suffix)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\common.py", line 95, in _copy_package_apps
    logger.warning(f"{hazard}  Overwriting file {str(dest)} with {str(src)}")
Message: '⚠️  Overwriting file C:\\Users\\dwales\\.local\\bin\\jupyter-lab.exe with C:\\Users\\dwales\\.local\\pipx\\venvs\\jupyterlab\\Scripts\\jupyter-lab.exe'
Arguments: ()
⚠️  Overwriting file C:\Users\dwales\.local\bin\jupyter-labextension.exe with C:\Users\dwales\.local\pipx\venvs\jupyterlab\Scripts\jupyter-labextension.exe
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>
Call stack:
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dwales\AppData\Local\Programs\Python\Python38\Scripts\pipx.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 759, in cli
    return run_pipx_command(parsed_pipx_args)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 216, in run_pipx_command
    return commands.upgrade(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 160, in upgrade
    _ = _upgrade_venv(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 125, in _upgrade_venv
    versions_updated += _upgrade_package(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 50, in _upgrade_package
    expose_apps_globally(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\common.py", line 56, in expose_apps_globally
    _copy_package_apps(local_bin_dir, app_paths, suffix=suffix)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\common.py", line 95, in _copy_package_apps
    logger.warning(f"{hazard}  Overwriting file {str(dest)} with {str(src)}")
Message: '⚠️  Overwriting file C:\\Users\\dwales\\.local\\bin\\jupyter-labextension.exe with C:\\Users\\dwales\\.local\\pipx\\venvs\\jupyterlab\\Scripts\\jupyter-labextension.exe'
Arguments: ()
⚠️  Overwriting file C:\Users\dwales\.local\bin\jupyter-labhub.exe with C:\Users\dwales\.local\pipx\venvs\jupyterlab\Scripts\jupyter-labhub.exe
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-37: character maps to <undefined>
Call stack:
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dwales\AppData\Local\Programs\Python\Python38\Scripts\pipx.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 759, in cli
    return run_pipx_command(parsed_pipx_args)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 216, in run_pipx_command
    return commands.upgrade(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 160, in upgrade
    _ = _upgrade_venv(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 125, in _upgrade_venv
    versions_updated += _upgrade_package(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\upgrade.py", line 50, in _upgrade_package
    expose_apps_globally(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\common.py", line 56, in expose_apps_globally
    _copy_package_apps(local_bin_dir, app_paths, suffix=suffix)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\common.py", line 95, in _copy_package_apps
    logger.warning(f"{hazard}  Overwriting file {str(dest)} with {str(src)}")
Message: '⚠️  Overwriting file C:\\Users\\dwales\\.local\\bin\\jupyter-labhub.exe with C:\\Users\\dwales\\.local\\pipx\\venvs\\jupyterlab\\Scripts\\jupyter-labhub.exe'
Arguments: ()
```

**Expected behavior**
The warning message should be printed without triggering an exception.

**Comment by itsayellow** [comment] 2021-03-16 00:40
Do I understand correctly that it successfully printed out the ⚠️ emoji to Powershell?

If that's the case, then it appears that even though stderr is utf-8, still somehow `logging` is using the cp1252 encoding when writing to the log file...?

**Comment by davidwales** [comment] 2021-03-16 00:42
That's correct. The emoji appeared in Powershell!

**Comment by itsayellow** [comment] 2021-03-16 00:51
Just to double check, which version of pipx are you using?
```
pipx --version
```

**Comment by davidwales** [comment] 2021-03-16 01:04
```
pipx --version
0.16.1.0
```

**Comment by itsayellow** [comment] 2021-03-16 01:10
Another thing that would be helpful is to let us know what the encoding is used in the output log file to verify that the problem is what I suspect it is.

The easiest way to do this is to open a log file in notepad.exe and then execute 'File -> Save As..' and see what it says in "encoding" at the bottom of the Save As.. Dialog.  Then report back which encoding is being used.

In powershell substitute `<timedatestamp>` in the following example with one of your log file's timedatestamps (you can probably just use tab to auto-complete any valid log file name):
```
notepad c:\users\dwales\.local\pipx\logs\cmd_<timedatestamp>.log
```

<img width="621" alt="Screen Shot 2021-03-15 at 6 07 42 PM" src="https://user-images.githubusercontent.com/12565784/111240999-7f881200-85b9-11eb-96d9-251432829acd.png">

**Comment by davidwales** [comment] 2021-03-16 01:20
The encoding appears to be UTF-8.

**Comment by itsayellow** [comment] 2021-03-16 01:48
Ok thanks that's really interesting but kind of confusing.  If utf-8 is being used in the log file then everything should work.  Somewhere encoding cp1252 is trying to be used, but if it's not the shell and it's not the log file then I'm confused.

The stacktrace references `python38\lib\logging\__init__.py", line 1084` is in `StreamHandler`, but unfortunately this is used both for itself to output to the shell, and also in `FileHandler` to output to the log file.  Frustratingly, there's no indication in the stacktrace which one is causing the error.

**Comment by itsayellow** [comment] 2021-03-16 01:50
On top of that I can't replicate this on my Windows using Powershell to examine what's happening.  It just works fine for me.

**Comment by itsayellow** [comment] 2021-03-16 01:51
Does the same error happen to you when using the following command:
```
pipx install -e pycowsay
```

That command should also generate a logging warning `⚠️  Ignoring --editable install option. pipx disallows it for anything but a local path, to avoid having to create a new src/ directory.`

If that causes the same error for you, it at least is an easier way to recreate this bug.

**Comment by davidwales** [comment] 2021-03-16 01:52
``` python
pipx install -e pycowsay
⚠️  Ignoring --editable install option. pipx disallows it for anything but a local path, to avoid having to create a new src/ directory.
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 46-47: character maps to <undefined>
Call stack:
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dwales\AppData\Local\Programs\Python\Python38\Scripts\pipx.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 759, in cli
    return run_pipx_command(parsed_pipx_args)
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\main.py", line 191, in run_pipx_command
    return commands.install(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\commands\install.py", line 60, in install
    venv.install_package(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\venv.py", line 223, in install_package
    (package_or_url, pip_args) = parse_specifier_for_install(
  File "c:\users\dwales\appdata\local\programs\python\python38\lib\site-packages\pipx\package_specifier.py", line 147, in parse_specifier_for_install
    logger.warning(
Message: '⚠️  Ignoring --editable install option. pipx disallows it for anything but a local path, to avoid having to create a new src/ directory.'
Arguments: ()
  installed package pycowsay 0.0.0.1, Python 3.8.7
  These apps are now globally available
    - pycowsay.exe
done! ✨ 🌟 ✨
```

**Comment by itsayellow** [comment] 2021-03-16 02:10
OK, it's possible the notepad trick doesn't actually work to tell what encoding the file is currently.  It may always just default to "utf-8".  I tested some files with different encodings and my Notepad always shows "utf-8" in the Save As.. dialog.

Ah, and I finally reproduced the error.  It doesn't seem to happen in Python 3.9, but it does in Python < 3.9.

**Comment by itsayellow** [comment] 2021-03-16 02:11
OK, I think I have a fix for this.

**Comment by itsayellow** [comment] 2021-03-16 02:24
Thanks for the bug report, this was good to know (and to fix).

**Comment by davidwales** [comment] 2021-03-16 03:22
Thank you for fixing it! I'm enjoying using pipx as a lightweight alternative to Conda.

**Closed** 2021-03-16 18:44 UTC
