### ISSUE TITLE
Any possible to backup the list of all installed and then install the list?

### ISSUE THREAD

**Issue by thepenguinthatwants** [pipxproject/pipx#156] opened 2019-05-05 06:21 UTC
Hiya!

I am just testing out pipx and it feels safer than pip --user.

Normally I can take backup and then install from it at pip by

```
pip freeze > requirements.txt
pip install --user -r requirements.txt
```
Are there similar ways to do it by pipx?

**Comment by funkyfuture** [comment] 2019-06-21 14:19
is this a duplicate of #109?

**Comment by cs01** [comment] 2020-03-12 16:47
> is this a duplicate of #109?

Yes, closing.

**Closed by cs01** 2020-03-12 16:47 UTC
