### ISSUE TITLE
pipx fails to install onelogin-aws-cli

### ISSUE THREAD

**Issue by skonakov-tophat** [pipxproject/pipx#169] opened 2019-05-30 15:57 UTC
When i run `pipx install --verbose onelogin-aws-cli`
I get:
```
pipx (run_pipx_command:125): Virtual Environment location is /home/skonakov/.local/pipx/venvs/onelogin-aws-cli
pipx (_run:124): running /home/skonakov/.pyenv/versions/3.7.3/bin/python3.7 -m venv /home/skonakov/.local/pipx/venvs/onelogin-aws-cli
pipx (_run:124): running /home/skonakov/.local/pipx/venvs/onelogin-aws-cli/bin/python -m pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, ....
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-19.1.1
pipx (_run:124): running /home/skonakov/.local/pipx/venvs/onelogin-aws-cli/bin/python -m pip install onelogin-aws-cli
Looking in indexes: https://pypi.org/simple, ...
Collecting onelogin-aws-cli
  Downloading https://files.pythonhosted.org/packages/77/e8/2ecb480aa88a47efd1b47484c61024249155f8d05f2faca71f94be8ac7b2/onelogin_aws_cli-0.1.16.tar.gz
Collecting ipify (from onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/6e/f0/eeeea218faaef1cd4db0ef7578ec43be1c9ea4e56fc2df797d4b0df8e2e7/ipify-1.0.0-py2.py3-none-any.whl
Collecting keyring (from onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/6e/b3/b4d443d2e30c00cdb73612426222172182e54359545cfb17774792619e49/keyring-19.0.2-py2.py3-none-any.whl
Collecting boto3 (from onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/cd/b0/8e67d52f8787370828709fe4cad39184e65f3fec28023b78c2556a04be0c/boto3-1.9.158-py2.py3-none-any.whl
Collecting onelogin (from onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/bc/79/d27b99b7b67b75a35c162cdaee5e79b5c9f7baf91a872f5a587b76b4d647/onelogin-1.8.1-py3-none-any.whl
Collecting backoff>=1.0.7 (from ipify->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/00/b9/b045f0fe02aa80cefc5a6921d5f7674db58c1658d0e4b888562c15ef6aba/backoff-1.8.0-py2.py3-none-any.whl
Collecting requests>=2.7.0 (from ipify->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting secretstorage; sys_platform == "linux" (from keyring->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/82/59/cb226752e20d83598d7fdcabd7819570b0329a61db07cfbdd21b2ef546e3/SecretStorage-3.1.1-py3-none-any.whl
Collecting entrypoints (from keyring->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting botocore<1.13.0,>=1.12.158 (from boto3->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/18/21/1e6f12ef2642786bda935f9936bfe3a3f19466a1f3f7e079053421a39f0a/botocore-1.12.158-py2.py3-none-any.whl
Collecting s3transfer<0.3.0,>=0.2.0 (from boto3->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/d7/de/5737f602e22073ecbded7a0c590707085e154e32b68d86545dcc31004c02/s3transfer-0.2.0-py2.py3-none-any.whl
Collecting defusedxml==0.5.0 (from onelogin->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Collecting python-dateutil==2.7.3 (from onelogin->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.7.0->ipify->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.7.0->ipify->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.7.0->ipify->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.7.0->ipify->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting jeepney (from secretstorage; sys_platform == "linux"->keyring->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/2b/f7/ff23b9b59534f501d47c327576aadda59da5b83d76ff837e6075bc325b9f/jeepney-0.4-py3-none-any.whl
Collecting cryptography (from secretstorage; sys_platform == "linux"->keyring->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/5b/12/b0409a94dad366d98a8eee2a77678c7a73aafd8c0e4b835abea634ea3896/cryptography-2.6.1-cp34-abi3-manylinux1_x86_64.whl
Collecting docutils>=0.10 (from botocore<1.13.0,>=1.12.158->boto3->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil==2.7.3->onelogin->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->secretstorage; sys_platform == "linux"->keyring->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->secretstorage; sys_platform == "linux"->keyring->onelogin-aws-cli)
  Using cached https://files.pythonhosted.org/packages/a0/ea/37fe21475c884f88a2ae496cab10e8f84f0cc11137be860af9eb37a3edb9/cffi-1.12.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->secretstorage; sys_platform == "linux"->keyring->onelogin-aws-cli)
ERROR: onelogin 1.8.1 has requirement requests==2.20.1, but you'll have requests 2.22.0 which is incompatible.
Installing collected packages: backoff, idna, chardet, urllib3, certifi, requests, ipify, jeepney, six, asn1crypto, pycparser, cffi, cryptography, secretstorage, entrypoints, keyring, jmespath, python-dateutil, docutils, botocore, s3transfer, boto3, defusedxml, onelogin, onelogin-aws-cli
Successfully installed asn1crypto-0.24.0 backoff-1.8.0 boto3-1.9.158 botocore-1.12.158 certifi-2019.3.9 cffi-1.12.3 chardet-3.0.4 cryptography-2.6.1 defusedxml-0.5.0 docutils-0.14 entrypoints-0.3 idna-2.8 ipify-1.0.0 jeepney-0.4 jmespath-0.9.4 keyring-19.0.2 onelogin-1.8.1 onelogin-aws-cli-0.1.16 pycparser-2.19 python-dateutil-2.7.3 requests-2.22.0 s3transfer-0.2.0 secretstorage-3.1.1 six-1.12.0 urllib3-1.25.3
pipx (rmdir:25): removing directory /home/skonakov/.local/pipx/venvs/onelogin-aws-cli
Could not find package onelogin-aws-cli. Is the name correct?
```

Looks like install succeeds but pipx can't find the package afterwards?

**Comment by cs01** [comment] 2019-08-03 16:13
Thanks for reporting, looks like a (corner case) bug in pipx's logic to discover entry points in packages.

**Comment by itsayellow** [comment] 2020-01-22 03:30
This works for me on macOS 10.15.2 and pipx v0.15.1.3.
```
  installed package onelogin-aws-cli 0.1.16, Python 3.7.6
  These apps are now globally available
    - onelogin-aws-login
done! ✨ 🌟 ✨
```

@skonakov-tophat , does it still fail for you?  Can we close this issue?

**Comment by itsayellow** [comment] 2020-02-11 22:04
Closing since we cannot reproduce in current version.

**Closed by itsayellow** 2020-02-11 22:04 UTC
