### ISSUE TITLE
Ability to install and run modules

### ISSUE THREAD

**Issue by FFY00** [pipxproject/pipx#517] opened 2020-10-07 17:22 UTC
**How would this feature be useful?**
This would be useful for projects that don't have an entrypoint but have a runnable module.

**Describe the solution you'd like**
Add a `-m`/`--module` argument to `pipx install` to install as a module and a `-m` argument to `pipx` to run the module.

Example
```
$ pipx install -m build  # install build as module
$ pipx -m build  # run the build module
```

The pip/Python equivalent
```
$ pip install build
$ python -m build
```

Related: https://github.com/FFY00/python-build/issues/101

**Comment by layday** [comment] 2020-10-08 16:18
Probably a duplicate of https://github.com/pipxproject/pipx/issues/177, which was filed for build's precursor.

**Closed** 2020-10-08 16:40 UTC

**Comment by cs01** [comment] 2020-10-08 16:49
@gaborbernat please add a comment explaining why you close an issue before you do so

**Comment by gaborbernat** [comment] 2020-10-08 16:58
Merged the topic in #177, which is the original request.
